version: 2
updates:
  # BACKEND (.NET)
  - package-ecosystem: "nuget"
    directory: "/Back/Back.API"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"

  - package-ecosystem: "nuget"
    directory: "/Back/Back.Application"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"

  - package-ecosystem: "nuget"
    directory: "/Back/Back.Domain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"

  - package-ecosystem: "nuget"
    directory: "/Back/Back.Infrastructure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"

  # FRONTEND (Next.js + TypeScript em /front)
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
