version: 2
updates:
  # Back.API
  - package-ecosystem: "nuget"
    directory: "/Back.API"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    groups:
      dependencias-back-api:
        patterns:
          - "*"

  # Back.Application
  - package-ecosystem: "nuget"
    directory: "/Back.Application"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    groups:
      dependencias-back-application:
        patterns:
          - "*"

  # Back.Domain
  - package-ecosystem: "nuget"
    directory: "/Back.Domain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    groups:
      dependencias-back-domain:
        patterns:
          - "*"

  # Frontend
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    groups:
      dependencias-front:
        patterns:
          - "*"
