version: '3.8'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: horas-discentes_frontend:latest  
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:5000"
    depends_on:
      - backend
      - db
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: ./Back/Dockerfile
    image: horas-discentes_backend:latest   
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://horas_discentes_user:senha_segura@db:5432/horas_discentes_db"
    depends_on:
      - db
    networks:
      - app-network
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: horas-discentes_db:latest        
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: horas_discentes_user
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: horas_discentes_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: