version: '3.8'

services:
  frontend:
    image: ghcr.io/ifpebj-ti/horas-discentes-frontend:latest  
    ports:
      - "${PORT_MACHINE_FRONTEND}:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_URL}
    depends_on:
      - backend
    networks:
      - rede-front
    restart: unless-stopped

  backend:
    image: ghcr.io/ifpebj-ti/horas-discentes-backend:latest 
    ports:
      - "${PORT_MACHINE_BACKEND}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    networks:
      - rede-front
      - rede-back
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: horas-discentes-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: horas_discentes_user
      POSTGRES_PASSWORD: 91188982
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rede-back
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:latest
    container_name: horas-discentes-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - rede-back
      - rede-front
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  db_data:

networks:
  rede-back:
  rede-front:
