services:
  nginx:
    image: nginx:latest
    container_name: horas-discentes-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certbot/certbot-data/live/:/etc/letsencrypt/live
      - ./nginx/certbot/certbot-data/archive/:/etc/letsencrypt/archive
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
      - ./nginx/certbot/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
    networks:
      - rede-back
      - rede-front
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: horas-discentes-certbot
    volumes:
      - ./nginx/certbot/certbot-data/live/:/etc/letsencrypt/live
      - ./nginx/certbot/certbot-data/archive/:/etc/letsencrypt/archive
      - ./nginx/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ingrid.lauanne@gmail.com --agree-tos --expand -d horamais.site -d www.horamais.site -d api.horamais.site
    networks:
      - rede-front

  frontend:
    image: ghcr.io/ifpebj-ti/horas-discentes-frontend:latest
    ports:
      - "${PORT_MACHINE_FRONTEND}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      
    networks:
      - rede-front
    depends_on:
      - backend

  backend:
    image: ghcr.io/ifpebj-ti/horas-discentes-backend:latest
    ports:
      - "${PORT_MACHINE_BACKEND}:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}
      - JWT__Key=${JWT__Key}
      - JWT__Issuer=${JWT__Issuer}
      - JWT__Audience=${JWT__Audience}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - EMAIL__Remetente=${EMAIL__Remetente}
      - EMAIL__Senha=${EMAIL__Senha}
      - EMAIL__Smtp=${EMAIL__Smtp}
      - EMAIL__Porta=${EMAIL__Porta}
      - COORDENADOR_CONVITE_LINK=${COORDENADOR_CONVITE_LINK}

    volumes:
      - backend_data_protection_keys:/root/.aspnet/DataProtection-Keys
    networks:
      - rede-back
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: horas-discentes-db
    ports:
      - "${PORT_MACHINE_DB}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rede-back
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  backend_data_protection_keys:

networks:
  rede-back:
  rede-front: