version: '3.8'

services:
  db:
    image: postgres:15
    container_name: horas-discentes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 91188982
      POSTGRES_DB: horas_discentes_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rede-back

  backend:
    build:
      context: .
      dockerfile: Back/Dockerfile
    container_name: horas-discentes-backend
    depends_on:
      - db
    ports:
      - "8080:8080"  # Porta interna exposta para o backend 
    networks:
      - rede-back

  frontend:
    build:
      context: ./front
    container_name: horas-discentes-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"  # Porta interna exposta para o frontend
    networks:
      - rede-front

  nginx:
    image: nginx:latest
    container_name: horas-discentes-nginx
    ports:
      - "80:80"  # Expondo a porta 80 do NGINX para o tráfego externo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mapear o arquivo nginx.conf
    networks:
      - rede-back
      - rede-front
    depends_on:
      - frontend
      - backend

volumes:
  db_data:

networks:
  rede-back:
  rede-front:
