services:
  db:
    image: postgres:15
    container_name: horas-discentes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 91188982
      POSTGRES_DB: horas_discentes_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rede-back

  backend:
    build:
      context: .
      dockerfile: Back/Dockerfile
    container_name: horas-discentes-backend
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      - rede-back

  frontend:
    build:
      context: ./front
    container_name: horas-discentes-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - rede-front

volumes:
  db_data:

networks:
  rede-back:
  rede-front:
