version: '3.8'

services:
  frontend:
    image: horas-discentes_frontend:latest  
    ports:
      - "${PORT_MACHINE_FRONTEND}:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_URL}
    depends_on:
      - backend
    networks:
      - rede-front
    restart: unless-stopped

  backend:
    image: horas-discentes_backend:latest   
    ports:
      - "${PORT_MACHINE_BACKEND}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    networks:
      - rede-front
      - rede-back
    restart: unless-stopped

  db: 
    image: postgres:15
    ports:
      - "${PORT_MACHINE_DB}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rede-back
    restart: unless-stopped

networks:
  rede-front:
  rede-back:

volumes:
  db_data:
