import type { Metadata } from 'next';

import './globals.css';
interface ClientProvidersProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: 'Horas Discentes',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ClientProviders = ({ children }: ClientProvidersProps) => {
    return <>{children}</>;
  };

  return (
    <html lang="pt-br">
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
