import type { Metadata } from 'next';
import './globals.css';

import ClientProviders from '@/components/ClientProviders';
import Version from '@/components/Version/Version';

export const metadata: Metadata = {
  title: 'Hora +',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="flex flex-col min-h-screen">
        {/* Providers e conteúdo da página */}
        <ClientProviders>
          <main className="flex-1">{children}</main>
        </ClientProviders>

        {/* Rodapé fixo com versão */}
        <footer className="p-4 border-t text-center text-sm text-gray-600">
          <Version />
        </footer>
      </body>
    </html>
  );
}
