name: Backend CI (.NET)

on:
  push:
    branches: ["main"]
    paths:
      - 'Back/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]
    paths:
      - 'Back/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Clonar repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📥 Instalar o SDK do .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 🛠️ Restaurar dependências
        run: |
          cd Back/Back.API
          dotnet restore Back.sln

      - name: 🏗️ Compilar a aplicação
        run: |
          cd Back/Back.API
          dotnet build Back.sln --no-restore

      # - name: ✅ Rodar testes
      #   run: |
      #     cd Back/Back.API
      #     dotnet test Back.sln --no-build --configuration Release
