name: Frontend CI

on:
  push:
    branches: ["main"]
    paths:
      - 'front/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: 🔄 Clonar repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🔍 Auditoria de segurança (npm)
        run: npm audit --audit-level=high

      - name: 🛠️ Build do projeto
        run: npm run build

      - name: ✅ Testes (opcional)
        run: npm test
        continue-on-error: true
