name: Pull requests CI

on:
  pull_request:
    paths:
      - 'front/**'
      - 'Back/**'

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Run ESLint
        run: |
          cd front
          npm run lint

      - name: Run Build
        run: |
          cd front
          docker build -t horasdiscentes-frontend:latest .

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Scan Docker image (Docker Scout)
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout quickview horasdiscentes-frontend:latest
          docker scout cves "-only-severity critical --exit-code 1 horasdiscentes-frontend:latest || exit 0"

  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: |
          cd Back
          dotnet restore

      - name: Run Build
        run: |
          cd Back
          docker build -t horasdiscentes-backend:latest .

      - name: Run Tests
        run: |
          cd Back
          echo "Ainda não tem testes"

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Scan Docker image (Docker Scout)
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout quickview horasdiscentes-backend:latest
          docker scout cves "-only-severity critical --exit-code 1 horasdiscentes-backend:latest || exit 0"
