name: CI/CD Principal

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-deploy-backend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: CI/CD de back-end

    steps:
      - uses: actions/checkout@v4

      - name: Login do Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Criar e enviar imagens do Docker
        uses: docker/build-push-action@v5
        with:
          context: ./Back
          push: true
          tags: horasdiscentes/backend:0.0.0

  build-and-deploy-frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: CI/CD de front-end

    steps:
      - uses: actions/checkout@v4

      - name: Login do Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Criar e enviar imagens do Docker
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: horasdiscentes/frontend:0.0.0

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Criar release

    steps:
      - uses: actions/checkout@v4

      - name: Publicar release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
