name: Generate Vulnerability Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Obter número de vulnerabilidades via GraphQL
        id: get_vulnerabilities
        run: |
          QUERY='{ repository(owner: "ingriidssantoss", name: "horas-discentes") { vulnerabilityAlerts(first: 100, states: OPEN) { totalCount } } }'
          RESPONSE=$(curl -s -H "Authorization: bearer ${{ secrets.GH_TOKEN }}" -X POST -d "{\"query\": \"$QUERY\"}" https://api.github.com/graphql)
          COUNT=$(echo "$RESPONSE" | jq '.data.repository.vulnerabilityAlerts.totalCount')
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Gerar badge SVG
        run: |
          COUNT=${{ steps.get_vulnerabilities.outputs.count }}
          COLOR="brightgreen"
          if [ "$COUNT" -gt 0 ]; then
            COLOR="red"
          fi
          echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"20\">
            <rect width=\"200\" height=\"20\" fill=\"$COLOR\"/>
            <text x=\"100\" y=\"14\" fill=\"#fff\" text-anchor=\"middle\" font-family=\"Verdana\" font-size=\"12\">
              Vulnerabilities: $COUNT
            </text>
          </svg>" > badge.svg

      - name: Commit e push do badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badge.svg
          git commit -m "Atualizar badge de vulnerabilidades" || echo "Nenhuma alteração no badge"
          git push
