name: Generate Vulnerability Badge

on:
  schedule:
    - cron: '0 12 * * *' # roda todo dia às 12h
  workflow_dispatch:

permissions:
  contents: write      # permite push
  security-events: read # permite ler vulnerabilidades

jobs:
  gerar-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Obter contagem de vulnerabilidades
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Buscando vulnerabilidades no repositório: $REPO"

          VULN_COUNT=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/dependabot/alerts" | jq '[.[] | select(.state=="open")] | length')

          echo "Encontradas $VULN_COUNT vulnerabilidades"

          COLOR="brightgreen"
          if [ "$VULN_COUNT" -gt 0 ]; then
            COLOR="red"
          fi

          echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV
          echo "COLOR=$COLOR" >> $GITHUB_ENV

      - name: Gerar badge com Shields.io
        run: |
          mkdir -p badges
          curl -s "https://img.shields.io/badge/Vulnerabilidades-${VULN_COUNT}-${COLOR}.svg" -o badges/vulnerabilidades.svg

      - name: Commit e Push da badge
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add badges/vulnerabilidades.svg
          git commit -m "Atualiza badge de vulnerabilidades: $VULN_COUNT" || echo "Nada para commitar"
          git push
