name: Badge de Vulnerabilidades [TEMP]

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todos os dias às 12h UTC
  workflow_dispatch:

jobs:
  gerar-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Obter contagem de vulnerabilidades
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Buscando vulnerabilidades no repositório: $REPO"

          VULN_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO/dependabot/alerts | jq length)

          echo "Encontradas $VULN_COUNT vulnerabilidades"

          COLOR="brightgreen"
          if [ "$VULN_COUNT" -gt 0 ]; then
            COLOR="red"
          fi

          echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV
          echo "COLOR=$COLOR" >> $GITHUB_ENV

      - name: Gerar badge com Shields.io
        run: |
          mkdir -p badges
          curl "https://img.shields.io/badge/Vulnerabilidades-$VULN_COUNT-$COLOR" -o badges/vulnerabilidades.svg



      - name: Commit e Push da badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"


          git add badges/vulnerabilidades.svg
          git commit -m "Atualiza badge de vulnerabilidades: $VULN_COUNT" || echo "Nada para commitar"
          git push
